//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityCustomized.ParsGreenSms {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://ParsGreen.com/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://ParsGreen.com/", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ParsGreen.com/", ConfigurationName="ParsGreenSms.SendSMSSoap")]
    public interface SendSMSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/MessageInfo", ReplyAction="*")]
        IdentityCustomized.ParsGreenSms.MessageInfoResponse MessageInfo(IdentityCustomized.ParsGreenSms.MessageInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/MessageInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.MessageInfoResponse> MessageInfoAsync(IdentityCustomized.ParsGreenSms.MessageInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/SendGroupSMS", ReplyAction="*")]
        IdentityCustomized.ParsGreenSms.SendGroupSMSResponse SendGroupSMS(IdentityCustomized.ParsGreenSms.SendGroupSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/SendGroupSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.SendGroupSMSResponse> SendGroupSMSAsync(IdentityCustomized.ParsGreenSms.SendGroupSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/SendGroupSMSP2P", ReplyAction="*")]
        IdentityCustomized.ParsGreenSms.SendGroupSMSP2PResponse SendGroupSMSP2P(IdentityCustomized.ParsGreenSms.SendGroupSMSP2PRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/SendGroupSMSP2P", ReplyAction="*")]
        System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.SendGroupSMSP2PResponse> SendGroupSMSP2PAsync(IdentityCustomized.ParsGreenSms.SendGroupSMSP2PRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/SendToGroup", ReplyAction="*")]
        IdentityCustomized.ParsGreenSms.SendToGroupResponse SendToGroup(IdentityCustomized.ParsGreenSms.SendToGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/SendToGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.SendToGroupResponse> SendToGroupAsync(IdentityCustomized.ParsGreenSms.SendToGroupRequest request);
        
        // CODEGEN: Generating message contract since element name signature from namespace http://ParsGreen.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/SendGroupSmsSimple", ReplyAction="*")]
        IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleResponse SendGroupSmsSimple(IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/SendGroupSmsSimple", ReplyAction="*")]
        System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleResponse> SendGroupSmsSimpleAsync(IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleRequest request);
        
        // CODEGEN: Generating message contract since element name signature from namespace http://ParsGreen.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/GetDelivery", ReplyAction="*")]
        IdentityCustomized.ParsGreenSms.GetDeliveryResponse GetDelivery(IdentityCustomized.ParsGreenSms.GetDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/GetDelivery", ReplyAction="*")]
        System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.GetDeliveryResponse> GetDeliveryAsync(IdentityCustomized.ParsGreenSms.GetDeliveryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/GetSMSNumbers", ReplyAction="*")]
        IdentityCustomized.ParsGreenSms.GetSMSNumbersResponse GetSMSNumbers(IdentityCustomized.ParsGreenSms.GetSMSNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ParsGreen.com/GetSMSNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.GetSMSNumbersResponse> GetSMSNumbersAsync(IdentityCustomized.ParsGreenSms.GetSMSNumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageInfo", Namespace="http://ParsGreen.com/", Order=0)]
        public IdentityCustomized.ParsGreenSms.MessageInfoRequestBody Body;
        
        public MessageInfoRequest() {
        }
        
        public MessageInfoRequest(IdentityCustomized.ParsGreenSms.MessageInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class MessageInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MsgBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int part;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool isUnicode;
        
        public MessageInfoRequestBody() {
        }
        
        public MessageInfoRequestBody(string signature, string MsgBody, int part, bool isUnicode) {
            this.signature = signature;
            this.MsgBody = MsgBody;
            this.part = part;
            this.isUnicode = isUnicode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageInfoResponse", Namespace="http://ParsGreen.com/", Order=0)]
        public IdentityCustomized.ParsGreenSms.MessageInfoResponseBody Body;
        
        public MessageInfoResponse() {
        }
        
        public MessageInfoResponse(IdentityCustomized.ParsGreenSms.MessageInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class MessageInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double MessageInfoResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int part;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool isUnicode;
        
        public MessageInfoResponseBody() {
        }
        
        public MessageInfoResponseBody(double MessageInfoResult, int part, bool isUnicode) {
            this.MessageInfoResult = MessageInfoResult;
            this.part = part;
            this.isUnicode = isUnicode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendGroupSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendGroupSMS", Namespace="http://ParsGreen.com/", Order=0)]
        public IdentityCustomized.ParsGreenSms.SendGroupSMSRequestBody Body;
        
        public SendGroupSMSRequest() {
        }
        
        public SendGroupSMSRequest(IdentityCustomized.ParsGreenSms.SendGroupSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendGroupSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public IdentityCustomized.ParsGreenSms.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isFlash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string udh;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int success;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public IdentityCustomized.ParsGreenSms.ArrayOfString retStr;
        
        public SendGroupSMSRequestBody() {
        }
        
        public SendGroupSMSRequestBody(string signature, string from, IdentityCustomized.ParsGreenSms.ArrayOfString to, string text, bool isFlash, string udh, int success, IdentityCustomized.ParsGreenSms.ArrayOfString retStr) {
            this.signature = signature;
            this.from = from;
            this.to = to;
            this.text = text;
            this.isFlash = isFlash;
            this.udh = udh;
            this.success = success;
            this.retStr = retStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendGroupSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendGroupSMSResponse", Namespace="http://ParsGreen.com/", Order=0)]
        public IdentityCustomized.ParsGreenSms.SendGroupSMSResponseBody Body;
        
        public SendGroupSMSResponse() {
        }
        
        public SendGroupSMSResponse(IdentityCustomized.ParsGreenSms.SendGroupSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendGroupSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendGroupSMSResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int success;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public IdentityCustomized.ParsGreenSms.ArrayOfString retStr;
        
        public SendGroupSMSResponseBody() {
        }
        
        public SendGroupSMSResponseBody(int SendGroupSMSResult, int success, IdentityCustomized.ParsGreenSms.ArrayOfString retStr) {
            this.SendGroupSMSResult = SendGroupSMSResult;
            this.success = success;
            this.retStr = retStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendGroupSMSP2PRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendGroupSMSP2P", Namespace="http://ParsGreen.com/", Order=0)]
        public IdentityCustomized.ParsGreenSms.SendGroupSMSP2PRequestBody Body;
        
        public SendGroupSMSP2PRequest() {
        }
        
        public SendGroupSMSP2PRequest(IdentityCustomized.ParsGreenSms.SendGroupSMSP2PRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendGroupSMSP2PRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public IdentityCustomized.ParsGreenSms.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public IdentityCustomized.ParsGreenSms.ArrayOfString texts;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isFlash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string udh;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public IdentityCustomized.ParsGreenSms.ArrayOfInt status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public IdentityCustomized.ParsGreenSms.ArrayOfInt success;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public IdentityCustomized.ParsGreenSms.ArrayOfString retStr;
        
        public SendGroupSMSP2PRequestBody() {
        }
        
        public SendGroupSMSP2PRequestBody(string signature, string from, IdentityCustomized.ParsGreenSms.ArrayOfString to, IdentityCustomized.ParsGreenSms.ArrayOfString texts, bool isFlash, string udh, IdentityCustomized.ParsGreenSms.ArrayOfInt status, IdentityCustomized.ParsGreenSms.ArrayOfInt success, IdentityCustomized.ParsGreenSms.ArrayOfString retStr) {
            this.signature = signature;
            this.from = from;
            this.to = to;
            this.texts = texts;
            this.isFlash = isFlash;
            this.udh = udh;
            this.status = status;
            this.success = success;
            this.retStr = retStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendGroupSMSP2PResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendGroupSMSP2PResponse", Namespace="http://ParsGreen.com/", Order=0)]
        public IdentityCustomized.ParsGreenSms.SendGroupSMSP2PResponseBody Body;
        
        public SendGroupSMSP2PResponse() {
        }
        
        public SendGroupSMSP2PResponse(IdentityCustomized.ParsGreenSms.SendGroupSMSP2PResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendGroupSMSP2PResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendGroupSMSP2PResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public IdentityCustomized.ParsGreenSms.ArrayOfInt status;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public IdentityCustomized.ParsGreenSms.ArrayOfInt success;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public IdentityCustomized.ParsGreenSms.ArrayOfString retStr;
        
        public SendGroupSMSP2PResponseBody() {
        }
        
        public SendGroupSMSP2PResponseBody(int SendGroupSMSP2PResult, IdentityCustomized.ParsGreenSms.ArrayOfInt status, IdentityCustomized.ParsGreenSms.ArrayOfInt success, IdentityCustomized.ParsGreenSms.ArrayOfString retStr) {
            this.SendGroupSMSP2PResult = SendGroupSMSP2PResult;
            this.status = status;
            this.success = success;
            this.retStr = retStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendToGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendToGroup", Namespace="http://ParsGreen.com/", Order=0)]
        public IdentityCustomized.ParsGreenSms.SendToGroupRequestBody Body;
        
        public SendToGroupRequest() {
        }
        
        public SendToGroupRequest(IdentityCustomized.ParsGreenSms.SendToGroupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendToGroupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string groupIdEncrypt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isFlash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string udh;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int success;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public IdentityCustomized.ParsGreenSms.ArrayOfString retStr;
        
        public SendToGroupRequestBody() {
        }
        
        public SendToGroupRequestBody(string signature, string from, string groupIdEncrypt, string text, bool isFlash, string udh, int success, IdentityCustomized.ParsGreenSms.ArrayOfString retStr) {
            this.signature = signature;
            this.from = from;
            this.groupIdEncrypt = groupIdEncrypt;
            this.text = text;
            this.isFlash = isFlash;
            this.udh = udh;
            this.success = success;
            this.retStr = retStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendToGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendToGroupResponse", Namespace="http://ParsGreen.com/", Order=0)]
        public IdentityCustomized.ParsGreenSms.SendToGroupResponseBody Body;
        
        public SendToGroupResponse() {
        }
        
        public SendToGroupResponse(IdentityCustomized.ParsGreenSms.SendToGroupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendToGroupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendToGroupResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int success;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public IdentityCustomized.ParsGreenSms.ArrayOfString retStr;
        
        public SendToGroupResponseBody() {
        }
        
        public SendToGroupResponseBody(int SendToGroupResult, int success, IdentityCustomized.ParsGreenSms.ArrayOfString retStr) {
            this.SendToGroupResult = SendToGroupResult;
            this.success = success;
            this.retStr = retStr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendGroupSmsSimpleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendGroupSmsSimple", Namespace="http://ParsGreen.com/", Order=0)]
        public IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleRequestBody Body;
        
        public SendGroupSmsSimpleRequest() {
        }
        
        public SendGroupSmsSimpleRequest(IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendGroupSmsSimpleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string from;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public IdentityCustomized.ParsGreenSms.ArrayOfString to;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string text;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isFlash;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string udh;
        
        public SendGroupSmsSimpleRequestBody() {
        }
        
        public SendGroupSmsSimpleRequestBody(string signature, string from, IdentityCustomized.ParsGreenSms.ArrayOfString to, string text, bool isFlash, string udh) {
            this.signature = signature;
            this.from = from;
            this.to = to;
            this.text = text;
            this.isFlash = isFlash;
            this.udh = udh;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendGroupSmsSimpleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendGroupSmsSimpleResponse", Namespace="http://ParsGreen.com/", Order=0)]
        public IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleResponseBody Body;
        
        public SendGroupSmsSimpleResponse() {
        }
        
        public SendGroupSmsSimpleResponse(IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class SendGroupSmsSimpleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SendGroupSmsSimpleResult;
        
        public SendGroupSmsSimpleResponseBody() {
        }
        
        public SendGroupSmsSimpleResponseBody(int SendGroupSmsSimpleResult) {
            this.SendGroupSmsSimpleResult = SendGroupSmsSimpleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeliveryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDelivery", Namespace="http://ParsGreen.com/", Order=0)]
        public IdentityCustomized.ParsGreenSms.GetDeliveryRequestBody Body;
        
        public GetDeliveryRequest() {
        }
        
        public GetDeliveryRequest(IdentityCustomized.ParsGreenSms.GetDeliveryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class GetDeliveryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string recId;
        
        public GetDeliveryRequestBody() {
        }
        
        public GetDeliveryRequestBody(string signature, string recId) {
            this.signature = signature;
            this.recId = recId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeliveryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeliveryResponse", Namespace="http://ParsGreen.com/", Order=0)]
        public IdentityCustomized.ParsGreenSms.GetDeliveryResponseBody Body;
        
        public GetDeliveryResponse() {
        }
        
        public GetDeliveryResponse(IdentityCustomized.ParsGreenSms.GetDeliveryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class GetDeliveryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetDeliveryResult;
        
        public GetDeliveryResponseBody() {
        }
        
        public GetDeliveryResponseBody(int GetDeliveryResult) {
            this.GetDeliveryResult = GetDeliveryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSMSNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSMSNumbers", Namespace="http://ParsGreen.com/", Order=0)]
        public IdentityCustomized.ParsGreenSms.GetSMSNumbersRequestBody Body;
        
        public GetSMSNumbersRequest() {
        }
        
        public GetSMSNumbersRequest(IdentityCustomized.ParsGreenSms.GetSMSNumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class GetSMSNumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string signature;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int numberType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public IdentityCustomized.ParsGreenSms.ArrayOfString numbers;
        
        public GetSMSNumbersRequestBody() {
        }
        
        public GetSMSNumbersRequestBody(string signature, int numberType, IdentityCustomized.ParsGreenSms.ArrayOfString numbers) {
            this.signature = signature;
            this.numberType = numberType;
            this.numbers = numbers;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSMSNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSMSNumbersResponse", Namespace="http://ParsGreen.com/", Order=0)]
        public IdentityCustomized.ParsGreenSms.GetSMSNumbersResponseBody Body;
        
        public GetSMSNumbersResponse() {
        }
        
        public GetSMSNumbersResponse(IdentityCustomized.ParsGreenSms.GetSMSNumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ParsGreen.com/")]
    public partial class GetSMSNumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetSMSNumbersResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public IdentityCustomized.ParsGreenSms.ArrayOfString numbers;
        
        public GetSMSNumbersResponseBody() {
        }
        
        public GetSMSNumbersResponseBody(int GetSMSNumbersResult, IdentityCustomized.ParsGreenSms.ArrayOfString numbers) {
            this.GetSMSNumbersResult = GetSMSNumbersResult;
            this.numbers = numbers;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSMSSoapChannel : IdentityCustomized.ParsGreenSms.SendSMSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSMSSoapClient : System.ServiceModel.ClientBase<IdentityCustomized.ParsGreenSms.SendSMSSoap>, IdentityCustomized.ParsGreenSms.SendSMSSoap {
        
        public SendSMSSoapClient() {
        }
        
        public SendSMSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSMSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdentityCustomized.ParsGreenSms.MessageInfoResponse IdentityCustomized.ParsGreenSms.SendSMSSoap.MessageInfo(IdentityCustomized.ParsGreenSms.MessageInfoRequest request) {
            return base.Channel.MessageInfo(request);
        }
        
        public double MessageInfo(string signature, string MsgBody, ref int part, ref bool isUnicode) {
            IdentityCustomized.ParsGreenSms.MessageInfoRequest inValue = new IdentityCustomized.ParsGreenSms.MessageInfoRequest();
            inValue.Body = new IdentityCustomized.ParsGreenSms.MessageInfoRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.MsgBody = MsgBody;
            inValue.Body.part = part;
            inValue.Body.isUnicode = isUnicode;
            IdentityCustomized.ParsGreenSms.MessageInfoResponse retVal = ((IdentityCustomized.ParsGreenSms.SendSMSSoap)(this)).MessageInfo(inValue);
            part = retVal.Body.part;
            isUnicode = retVal.Body.isUnicode;
            return retVal.Body.MessageInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.MessageInfoResponse> IdentityCustomized.ParsGreenSms.SendSMSSoap.MessageInfoAsync(IdentityCustomized.ParsGreenSms.MessageInfoRequest request) {
            return base.Channel.MessageInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.MessageInfoResponse> MessageInfoAsync(string signature, string MsgBody, int part, bool isUnicode) {
            IdentityCustomized.ParsGreenSms.MessageInfoRequest inValue = new IdentityCustomized.ParsGreenSms.MessageInfoRequest();
            inValue.Body = new IdentityCustomized.ParsGreenSms.MessageInfoRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.MsgBody = MsgBody;
            inValue.Body.part = part;
            inValue.Body.isUnicode = isUnicode;
            return ((IdentityCustomized.ParsGreenSms.SendSMSSoap)(this)).MessageInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdentityCustomized.ParsGreenSms.SendGroupSMSResponse IdentityCustomized.ParsGreenSms.SendSMSSoap.SendGroupSMS(IdentityCustomized.ParsGreenSms.SendGroupSMSRequest request) {
            return base.Channel.SendGroupSMS(request);
        }
        
        public int SendGroupSMS(string signature, string from, IdentityCustomized.ParsGreenSms.ArrayOfString to, string text, bool isFlash, string udh, ref int success, ref IdentityCustomized.ParsGreenSms.ArrayOfString retStr) {
            IdentityCustomized.ParsGreenSms.SendGroupSMSRequest inValue = new IdentityCustomized.ParsGreenSms.SendGroupSMSRequest();
            inValue.Body = new IdentityCustomized.ParsGreenSms.SendGroupSMSRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.text = text;
            inValue.Body.isFlash = isFlash;
            inValue.Body.udh = udh;
            inValue.Body.success = success;
            inValue.Body.retStr = retStr;
            IdentityCustomized.ParsGreenSms.SendGroupSMSResponse retVal = ((IdentityCustomized.ParsGreenSms.SendSMSSoap)(this)).SendGroupSMS(inValue);
            success = retVal.Body.success;
            retStr = retVal.Body.retStr;
            return retVal.Body.SendGroupSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.SendGroupSMSResponse> IdentityCustomized.ParsGreenSms.SendSMSSoap.SendGroupSMSAsync(IdentityCustomized.ParsGreenSms.SendGroupSMSRequest request) {
            return base.Channel.SendGroupSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.SendGroupSMSResponse> SendGroupSMSAsync(string signature, string from, IdentityCustomized.ParsGreenSms.ArrayOfString to, string text, bool isFlash, string udh, int success, IdentityCustomized.ParsGreenSms.ArrayOfString retStr) {
            IdentityCustomized.ParsGreenSms.SendGroupSMSRequest inValue = new IdentityCustomized.ParsGreenSms.SendGroupSMSRequest();
            inValue.Body = new IdentityCustomized.ParsGreenSms.SendGroupSMSRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.text = text;
            inValue.Body.isFlash = isFlash;
            inValue.Body.udh = udh;
            inValue.Body.success = success;
            inValue.Body.retStr = retStr;
            return ((IdentityCustomized.ParsGreenSms.SendSMSSoap)(this)).SendGroupSMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdentityCustomized.ParsGreenSms.SendGroupSMSP2PResponse IdentityCustomized.ParsGreenSms.SendSMSSoap.SendGroupSMSP2P(IdentityCustomized.ParsGreenSms.SendGroupSMSP2PRequest request) {
            return base.Channel.SendGroupSMSP2P(request);
        }
        
        public int SendGroupSMSP2P(string signature, string from, IdentityCustomized.ParsGreenSms.ArrayOfString to, IdentityCustomized.ParsGreenSms.ArrayOfString texts, bool isFlash, string udh, ref IdentityCustomized.ParsGreenSms.ArrayOfInt status, ref IdentityCustomized.ParsGreenSms.ArrayOfInt success, ref IdentityCustomized.ParsGreenSms.ArrayOfString retStr) {
            IdentityCustomized.ParsGreenSms.SendGroupSMSP2PRequest inValue = new IdentityCustomized.ParsGreenSms.SendGroupSMSP2PRequest();
            inValue.Body = new IdentityCustomized.ParsGreenSms.SendGroupSMSP2PRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.texts = texts;
            inValue.Body.isFlash = isFlash;
            inValue.Body.udh = udh;
            inValue.Body.status = status;
            inValue.Body.success = success;
            inValue.Body.retStr = retStr;
            IdentityCustomized.ParsGreenSms.SendGroupSMSP2PResponse retVal = ((IdentityCustomized.ParsGreenSms.SendSMSSoap)(this)).SendGroupSMSP2P(inValue);
            status = retVal.Body.status;
            success = retVal.Body.success;
            retStr = retVal.Body.retStr;
            return retVal.Body.SendGroupSMSP2PResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.SendGroupSMSP2PResponse> IdentityCustomized.ParsGreenSms.SendSMSSoap.SendGroupSMSP2PAsync(IdentityCustomized.ParsGreenSms.SendGroupSMSP2PRequest request) {
            return base.Channel.SendGroupSMSP2PAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.SendGroupSMSP2PResponse> SendGroupSMSP2PAsync(string signature, string from, IdentityCustomized.ParsGreenSms.ArrayOfString to, IdentityCustomized.ParsGreenSms.ArrayOfString texts, bool isFlash, string udh, IdentityCustomized.ParsGreenSms.ArrayOfInt status, IdentityCustomized.ParsGreenSms.ArrayOfInt success, IdentityCustomized.ParsGreenSms.ArrayOfString retStr) {
            IdentityCustomized.ParsGreenSms.SendGroupSMSP2PRequest inValue = new IdentityCustomized.ParsGreenSms.SendGroupSMSP2PRequest();
            inValue.Body = new IdentityCustomized.ParsGreenSms.SendGroupSMSP2PRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.texts = texts;
            inValue.Body.isFlash = isFlash;
            inValue.Body.udh = udh;
            inValue.Body.status = status;
            inValue.Body.success = success;
            inValue.Body.retStr = retStr;
            return ((IdentityCustomized.ParsGreenSms.SendSMSSoap)(this)).SendGroupSMSP2PAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdentityCustomized.ParsGreenSms.SendToGroupResponse IdentityCustomized.ParsGreenSms.SendSMSSoap.SendToGroup(IdentityCustomized.ParsGreenSms.SendToGroupRequest request) {
            return base.Channel.SendToGroup(request);
        }
        
        public int SendToGroup(string signature, string from, string groupIdEncrypt, string text, bool isFlash, string udh, ref int success, ref IdentityCustomized.ParsGreenSms.ArrayOfString retStr) {
            IdentityCustomized.ParsGreenSms.SendToGroupRequest inValue = new IdentityCustomized.ParsGreenSms.SendToGroupRequest();
            inValue.Body = new IdentityCustomized.ParsGreenSms.SendToGroupRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.from = from;
            inValue.Body.groupIdEncrypt = groupIdEncrypt;
            inValue.Body.text = text;
            inValue.Body.isFlash = isFlash;
            inValue.Body.udh = udh;
            inValue.Body.success = success;
            inValue.Body.retStr = retStr;
            IdentityCustomized.ParsGreenSms.SendToGroupResponse retVal = ((IdentityCustomized.ParsGreenSms.SendSMSSoap)(this)).SendToGroup(inValue);
            success = retVal.Body.success;
            retStr = retVal.Body.retStr;
            return retVal.Body.SendToGroupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.SendToGroupResponse> IdentityCustomized.ParsGreenSms.SendSMSSoap.SendToGroupAsync(IdentityCustomized.ParsGreenSms.SendToGroupRequest request) {
            return base.Channel.SendToGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.SendToGroupResponse> SendToGroupAsync(string signature, string from, string groupIdEncrypt, string text, bool isFlash, string udh, int success, IdentityCustomized.ParsGreenSms.ArrayOfString retStr) {
            IdentityCustomized.ParsGreenSms.SendToGroupRequest inValue = new IdentityCustomized.ParsGreenSms.SendToGroupRequest();
            inValue.Body = new IdentityCustomized.ParsGreenSms.SendToGroupRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.from = from;
            inValue.Body.groupIdEncrypt = groupIdEncrypt;
            inValue.Body.text = text;
            inValue.Body.isFlash = isFlash;
            inValue.Body.udh = udh;
            inValue.Body.success = success;
            inValue.Body.retStr = retStr;
            return ((IdentityCustomized.ParsGreenSms.SendSMSSoap)(this)).SendToGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleResponse IdentityCustomized.ParsGreenSms.SendSMSSoap.SendGroupSmsSimple(IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleRequest request) {
            return base.Channel.SendGroupSmsSimple(request);
        }
        
        public int SendGroupSmsSimple(string signature, string from, IdentityCustomized.ParsGreenSms.ArrayOfString to, string text, bool isFlash, string udh) {
            IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleRequest inValue = new IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleRequest();
            inValue.Body = new IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.text = text;
            inValue.Body.isFlash = isFlash;
            inValue.Body.udh = udh;
            IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleResponse retVal = ((IdentityCustomized.ParsGreenSms.SendSMSSoap)(this)).SendGroupSmsSimple(inValue);
            return retVal.Body.SendGroupSmsSimpleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleResponse> IdentityCustomized.ParsGreenSms.SendSMSSoap.SendGroupSmsSimpleAsync(IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleRequest request) {
            return base.Channel.SendGroupSmsSimpleAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleResponse> SendGroupSmsSimpleAsync(string signature, string from, IdentityCustomized.ParsGreenSms.ArrayOfString to, string text, bool isFlash, string udh) {
            IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleRequest inValue = new IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleRequest();
            inValue.Body = new IdentityCustomized.ParsGreenSms.SendGroupSmsSimpleRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.from = from;
            inValue.Body.to = to;
            inValue.Body.text = text;
            inValue.Body.isFlash = isFlash;
            inValue.Body.udh = udh;
            return ((IdentityCustomized.ParsGreenSms.SendSMSSoap)(this)).SendGroupSmsSimpleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdentityCustomized.ParsGreenSms.GetDeliveryResponse IdentityCustomized.ParsGreenSms.SendSMSSoap.GetDelivery(IdentityCustomized.ParsGreenSms.GetDeliveryRequest request) {
            return base.Channel.GetDelivery(request);
        }
        
        public int GetDelivery(string signature, string recId) {
            IdentityCustomized.ParsGreenSms.GetDeliveryRequest inValue = new IdentityCustomized.ParsGreenSms.GetDeliveryRequest();
            inValue.Body = new IdentityCustomized.ParsGreenSms.GetDeliveryRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.recId = recId;
            IdentityCustomized.ParsGreenSms.GetDeliveryResponse retVal = ((IdentityCustomized.ParsGreenSms.SendSMSSoap)(this)).GetDelivery(inValue);
            return retVal.Body.GetDeliveryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.GetDeliveryResponse> IdentityCustomized.ParsGreenSms.SendSMSSoap.GetDeliveryAsync(IdentityCustomized.ParsGreenSms.GetDeliveryRequest request) {
            return base.Channel.GetDeliveryAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.GetDeliveryResponse> GetDeliveryAsync(string signature, string recId) {
            IdentityCustomized.ParsGreenSms.GetDeliveryRequest inValue = new IdentityCustomized.ParsGreenSms.GetDeliveryRequest();
            inValue.Body = new IdentityCustomized.ParsGreenSms.GetDeliveryRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.recId = recId;
            return ((IdentityCustomized.ParsGreenSms.SendSMSSoap)(this)).GetDeliveryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        IdentityCustomized.ParsGreenSms.GetSMSNumbersResponse IdentityCustomized.ParsGreenSms.SendSMSSoap.GetSMSNumbers(IdentityCustomized.ParsGreenSms.GetSMSNumbersRequest request) {
            return base.Channel.GetSMSNumbers(request);
        }
        
        public int GetSMSNumbers(string signature, int numberType, ref IdentityCustomized.ParsGreenSms.ArrayOfString numbers) {
            IdentityCustomized.ParsGreenSms.GetSMSNumbersRequest inValue = new IdentityCustomized.ParsGreenSms.GetSMSNumbersRequest();
            inValue.Body = new IdentityCustomized.ParsGreenSms.GetSMSNumbersRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.numberType = numberType;
            inValue.Body.numbers = numbers;
            IdentityCustomized.ParsGreenSms.GetSMSNumbersResponse retVal = ((IdentityCustomized.ParsGreenSms.SendSMSSoap)(this)).GetSMSNumbers(inValue);
            numbers = retVal.Body.numbers;
            return retVal.Body.GetSMSNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.GetSMSNumbersResponse> IdentityCustomized.ParsGreenSms.SendSMSSoap.GetSMSNumbersAsync(IdentityCustomized.ParsGreenSms.GetSMSNumbersRequest request) {
            return base.Channel.GetSMSNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<IdentityCustomized.ParsGreenSms.GetSMSNumbersResponse> GetSMSNumbersAsync(string signature, int numberType, IdentityCustomized.ParsGreenSms.ArrayOfString numbers) {
            IdentityCustomized.ParsGreenSms.GetSMSNumbersRequest inValue = new IdentityCustomized.ParsGreenSms.GetSMSNumbersRequest();
            inValue.Body = new IdentityCustomized.ParsGreenSms.GetSMSNumbersRequestBody();
            inValue.Body.signature = signature;
            inValue.Body.numberType = numberType;
            inValue.Body.numbers = numbers;
            return ((IdentityCustomized.ParsGreenSms.SendSMSSoap)(this)).GetSMSNumbersAsync(inValue);
        }
    }
}
